name: windows

on:
  push:
    branches: [ master ]
  pull_request:
    paths-ignore:
      - .github/workflows/macos.yml
      - .github/workflows/ubuntu.yml

jobs:
  test-windows:
    name: Test on Ruby ${{ matrix.ruby }} Windows
    runs-on: windows-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6', '2.5', '2.4' ]
        experimental: [false]
        # Does not supported yet:
        # Ruby (< 2.7.dev, >= 2.3), which is required by gem 'nokogiri (~> 1.10)', is not
        #   available in the local ruby installation
        # include:
        #   - ruby: '2.7'
        #     experimental: true
    steps:
      - uses: actions/checkout@master
      - name: Use Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Update gems
        shell: pwsh
        run: |
          gem install bundler
          bundle config --local path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Install graphviz
        uses: nick-invision/retry@v1
        with:
          polling_interval_seconds: 5
          timeout_minutes: 5
          max_attempts: 3
          command: choco install --no-progress graphviz
      - name: Check dot command
        run: |
          dot -?
      - name: Run specs
        run: |
          bundle exec rake